[theme]
primaryColor = "#FF4B4B"                  # Red shade for buttons, sliders
backgroundColor = "#FDF6F0"               # Light beige background
secondaryBackgroundColor = "#FFFFFF"      # White containers
textColor = "#262730"                     # Dark text
font = "sans serif"                       # Options: "sans serif", "serif", "monospace"
